### ISSUE TITLE
"No such file or directory error" when looking for .tz file that it creates

### ISSUE THREAD

**Issue by carterkraft** [yandreev3/3dWiFiSend#1]
It seems to be chopping 2 letters off the file name which causes it to fail when it cant find the tz file. 
![image](https://user-images.githubusercontent.com/37340374/37349854-61e7b992-26a5-11e8-877e-93b01ed46d2e.png)

**Comment by yandreev3** [comment]
Just pushed a new updated file. Issue should be resolved. Tested on my system with the same filename + others. Let me know if it works for you.

**Comment by carterkraft** [comment]
Awesome stuff, that fixed it.
