### ISSUE TITLE
Unable to Send file to printer

### ISSUE THREAD

**Issue by carterkraft** [yandreev3/3dWiFiSend#2]
I watched the video and readme in detail but seems I can't get it to connect to the printer. 

![image](https://user-images.githubusercontent.com/37340374/38141415-ab05e85a-33fd-11e8-8570-614774d0f4ef.png)

**Comment by yandreev3** [comment]
Are you on wifi? If so, go ahead and give it another try using the ethernet cable. I get that error quite inconsistently on wifi.

**Comment by yandreev3** [comment]
Wait no your issue is your file location. As of this version, you have to have the file in the same folder as the python script because of naming/paths. This is something that i should fix but in the meantime, put the gcode file in the same folder and run   "python .\3DWiFiSendFile.py 192.168.1.114 Articulated_Butterfly.gcode yes"

**Comment by carterkraft** [comment]
Thanks for the help, but still the same error I have had the file in the same path. 

![image](https://user-images.githubusercontent.com/37340374/38152341-f097c3aa-342c-11e8-98da-6f19d158f3c2.png)

**Comment by carterkraft** [comment]
I should also note- I am able to successfully print through the QidiPrint Software through that IP.

**Comment by carterkraft** [comment]
So combining what you put here, with just putting the filename no path AND also removing the "-" from the name used in this attempt I was successful.  Articulated_Butterfly worked. Oddly the Qiditech software can't handle the "-" either.  

Thanks for all the hard work and help. Hopefully in case someone runs into the same issues I have they will be able to get it working.

**Comment by yandreev3** [comment]
The error is actually being returned from the printer. The printer itself does not like the filename; specifically special characters in it. That's why both the qidi software and this script return that error.
